% Matlab Soru Çözümleri ve Konu Anlatýmlarý
% alidemirkaya.net Gururla Sunar....
% Ýlgi ve Beðenileriniz Ýçin Teþekkür Ederiz...

% Matlab Soru Çözümleri 102-Grafik Çizimleri-2
% Öðrenci Vize-Final Notlarý-2
clear all
clc
veri_oku=xlsread('notort');
vizenotlari=veri_oku(:,1);
finalnotlari=veri_oku(:,2);
ortalamalari=veri_oku(:,3);
% Grafiklerini çizdirelim
% Grafik özellikleri þu þekilde
% plot(vizenotlari,'--bp',...
%     %Öncelikle Çizgi Kalýnlýði,
%     'LineWidth',1,...
%     % Ýþaretleyici Büyüklüðü    
%     'MarkerSize',6,...
%     % Ýþaretleyici Çizgi Rengi    
%     'MarkerEdgeColor','c',...
%     % Ýþaretleyici Taban Rengi
%     'MarkerFaceColor',[0.3,0.2,0.2])
plot(vizenotlari,'--bp',... 
    'LineWidth',1,...
    'MarkerSize',6,...    
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[0.3,0.2,0.2])
hold on
plot(finalnotlari,'--ys',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor',[0.3,0.2,0.2])
xlabel('Öðrenci Numarasý')
ylabel('Aldýðý Not')
legend('Vize','Final','Location','Southeast');

            