%  Matlab Soru Çözümleri ve Konu Anlatýmlarý
% alidemirkaya.net Gururla Sunar....
% Ýlgi ve Beðenileriniz Ýçin Teþekkür Ederiz...

% Matlab Soru Çözümleri 110-Grafik Çizimleri-10
% Enerji Tüketimi
clear all
clc
enerji_miktarlari=xlsread('enerji');
% Verileri Deðiþkenlere Atayalým
komur_tuketimi=enerji_miktarlari(:,1);
linyit_tuketimi=enerji_miktarlari(:,2);
odun_tuketimi=enerji_miktarlari(:,3);
% Grafikleri Çizdirelim
k_grafik=plot(komur_tuketimi,'-rs',... 
    'LineWidth',1,...
    'MarkerSize',5,...    
    'MarkerEdgeColor','y',...
    'MarkerFaceColor',[1,1,0]);
hold on
grid on
l_grafik=plot(linyit_tuketimi,'-bp',... 
    'LineWidth',1,...
    'MarkerSize',7,...    
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[1,0,0]);
o_grafik=plot(odun_tuketimi,'-y*',... 
    'LineWidth',1,...
    'MarkerSize',7,...    
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[1,0,0]);
% Eksen Baþlýklarý
xlabel('Bölge Numarasý');
ylabel('Tüketim Miktarý /ton');
title('1995 Yýlýna Ait Enerji Tüketimi')
legend('Kömür','Linyit','Odun')