% Matlab Soru Çözümleri ve Konu Anlatýmlarý
% alidemirkaya.net Gururla Sunar....
% Ýlgi ve Beðenileriniz Ýçin Teþekkür Ederiz...

% Matlab Soru Çözümleri 78-Temel Programlama-(16)
% Kelime Bulma 
clear all
clc
a1={'YCKMSCLQWNABDGQ';...
'NYOOPTÝMÝZASYON';...
'LCCNYIZKLAMWJEP';...
'IPCYTNAMETSATIÞ';...
'PLANLAMASVERÝMT';}
optimizasyon=strfind(a1,'OPTÝMÝZASYON')
satis=strfind(a1,'SATIÞ')
planlama=strfind(a1,'PLANLAMA')
verim=strfind(a1,'VERÝM')
